-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 00:51:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FAMILIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAMILIA` (
  `nombre` VARCHAR(40) NOT NULL,
  `incompatibilidades` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENFERMEDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENFERMEDAD` (
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_fam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `nombre_fam_idx` (`nombre_fam` ASC) VISIBLE,
  CONSTRAINT `nombre_fam`
    FOREIGN KEY (`nombre_fam`)
    REFERENCES `mydb`.`FAMILIA` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEDICAMENTO` (
  `codigo_med` INT NOT NULL,
  `precio` FLOAT NULL,
  `unidades_stock` VARCHAR(45) NULL,
  `unidades_vendidas` VARCHAR(45) NULL,
  `tipo_venta` SET('receta', 'libre') NULL,
  `tipo` SET('pomada', 'inyectable', 'jarabe', 'comprimido') NULL,
  `nombre_fam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_med`),
  INDEX `nombre_fam_idx` (`nombre_fam` ASC) VISIBLE,
  CONSTRAINT `nombre_fam`
    FOREIGN KEY (`nombre_fam`)
    REFERENCES `mydb`.`FAMILIA` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE_CREDITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE_CREDITO` (
  `DNI` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_pago` DATE NULL,
  `datos_bancarios` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `fecha_compra`
    FOREIGN KEY ()
    REFERENCES `mydb`.`VENTAS` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTAS` (
  `fecha_compra` DATE NOT NULL,
  `cantidades` INT NULL,
  `DNI_cliente` VARCHAR(45) NOT NULL,
  `cod_med` INT NOT NULL,
  PRIMARY KEY (`fecha_compra`),
  INDEX `DNI_cliente_idx` (`DNI_cliente` ASC) VISIBLE,
  INDEX `cod_med_idx` (`cod_med` ASC) VISIBLE,
  CONSTRAINT `DNI_cliente`
    FOREIGN KEY (`DNI_cliente`)
    REFERENCES `mydb`.`CLIENTE_CREDITO` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_med`
    FOREIGN KEY (`cod_med`)
    REFERENCES `mydb`.`MEDICAMENTO` (`codigo_med`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LABORATORIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LABORATORIO` (
  `codigo_lab` INT NOT NULL,
  `telefono` INT NULL,
  `fax` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_lab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA_MED_LAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA_MED_LAB` (
  `cod_med` INT NOT NULL,
  `cod_lab` INT NOT NULL,
  `persona_contacto` VARCHAR(45) NULL,
  `cantidades` INT NULL,
  PRIMARY KEY (`cod_med`, `cod_lab`),
  INDEX `cod_lab_idx` (`cod_lab` ASC) VISIBLE,
  CONSTRAINT `cod_med`
    FOREIGN KEY (`cod_med`)
    REFERENCES `mydb`.`MEDICAMENTO` (`codigo_med`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_lab`
    FOREIGN KEY (`cod_lab`)
    REFERENCES `mydb`.`LABORATORIO` (`codigo_lab`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FABRICA_MED_LAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FABRICA_MED_LAB` (
  `cod_med` INT NOT NULL,
  `cod_lab` INT NOT NULL,
  PRIMARY KEY (`cod_med`, `cod_lab`),
  INDEX `cod_lab_idx` (`cod_lab` ASC) VISIBLE,
  CONSTRAINT `cod_med0`
    FOREIGN KEY (`cod_med`)
    REFERENCES `mydb`.`MEDICAMENTO` (`codigo_med`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_lab0`
    FOREIGN KEY (`cod_lab`)
    REFERENCES `mydb`.`LABORATORIO` (`codigo_lab`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`FAMILIA`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`FAMILIA` (`nombre`, `incompatibilidades`) VALUES ('antialegrico', 'alcohol');
INSERT INTO `mydb`.`FAMILIA` (`nombre`, `incompatibilidades`) VALUES ('laxante', 'alcohol');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ENFERMEDAD`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ENFERMEDAD` (`nombre`, `nombre_fam`) VALUES ('gripe', 'antibiotico');
INSERT INTO `mydb`.`ENFERMEDAD` (`nombre`, `nombre_fam`) VALUES ('varicela', 'antipireticos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`MEDICAMENTO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`MEDICAMENTO` (`codigo_med`, `precio`, `unidades_stock`, `unidades_vendidas`, `tipo_venta`, `tipo`, `nombre_fam`) VALUES (0000, 10, '50', '10', 'receta', 'pomada', 'antibiotico');
INSERT INTO `mydb`.`MEDICAMENTO` (`codigo_med`, `precio`, `unidades_stock`, `unidades_vendidas`, `tipo_venta`, `tipo`, `nombre_fam`) VALUES (0001, 15, '40', '5', 'libre', 'jarabe', 'antidiarreico');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`CLIENTE_CREDITO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`CLIENTE_CREDITO` (`DNI`, `nombre`, `fecha_pago`, `datos_bancarios`) VALUES ('45454545p', 'Juan Salazar', '15/11/2018', '66548284554');
INSERT INTO `mydb`.`CLIENTE_CREDITO` (`DNI`, `nombre`, `fecha_pago`, `datos_bancarios`) VALUES ('21212121k', 'Pedro Castro', '28/11/2018', '98764188712');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`VENTAS`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`VENTAS` (`fecha_compra`, `cantidades`, `DNI_cliente`, `cod_med`) VALUES ('15/11/2018', 5, '45454545p', 0000);
INSERT INTO `mydb`.`VENTAS` (`fecha_compra`, `cantidades`, `DNI_cliente`, `cod_med`) VALUES ('18/11/2018', 2, '21212121k', 0001);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`LABORATORIO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`LABORATORIO` (`codigo_lab`, `telefono`, `fax`, `nombre`, `direccion`) VALUES (2222, 922963852, 2222222, 'Adeje Farmacias', 'av trinidad, 5');
INSERT INTO `mydb`.`LABORATORIO` (`codigo_lab`, `telefono`, `fax`, `nombre`, `direccion`) VALUES (2223, 922741359, 1111111, 'Maestre Farmacias', 'av calvo sotelo, 2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`COMPRA_MED_LAB`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`COMPRA_MED_LAB` (`cod_med`, `cod_lab`, `persona_contacto`, `cantidades`) VALUES (0000, 2222, 'Alejandro', 80);
INSERT INTO `mydb`.`COMPRA_MED_LAB` (`cod_med`, `cod_lab`, `persona_contacto`, `cantidades`) VALUES (0001, 2222, 'Jesus', 30);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`FABRICA_MED_LAB`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`FABRICA_MED_LAB` (`cod_med`, `cod_lab`) VALUES (0000, 2222);
INSERT INTO `mydb`.`FABRICA_MED_LAB` (`cod_med`, `cod_lab`) VALUES (0000, 1111);

COMMIT;

